[package]
name = "quest"
version = "0.1.0"
authors = ["Clement Rebut <clement.rebut@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    rand = "0.7.3"
    rand_distr = "0.2.2"
    lazy_static = "1.4.0"
